#ifndef CRC16_MODBUS_H
#define CRC16_MODBUS_H
/* Auto-generated by CrcEngine 0.2.0 */
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

uint16_t crc16_modbus(const uint8_t data[], size_t num_bytes);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* CRC16_MODBUS_H */
